#!/usr/bin/env bash
# Installs and configures HAproxy-2.0
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt -y install haproxy

FILE="/etc/haproxy/haproxy.cfg"

server_1="100.25.102.221"
server_2="34.229.70.103"

FRONTEND="\nfrontend scorprogfront\n\tbind *:80\n\tdefault_backend scorprogservers\n"
BACKEND="\nbackend scorprogservers\n\tbalance roundrobin\n\tserver server_1 $server_1\n\tserver server_2 $server_2\n"

echo -e "$FRONTEND" | sudo tee -a "$FILE" 
echo -e "$BACKEND" | sudo tee -a "$FILE"

sudo service haproxy restart
